remote_theme: pages-themes/dinky@v0.2.0
plugins:
  - jekyll-remote-theme

title: Your Research Website
description: My personal research site showcasing projects, lab capabilities, and qualifications.
